version: "3"
services:
    mongo:
        image: miguelangel299/practica2_gps:db
        deploy:
	        replicas: 1
	        resources:
	            limits:
	                cups: "0.15"
	                memory: 200M
	        restart_policy:
	            condition: on-failure
        ports:
	        - "28017:28017"
	        - "27017:27017"
        volumes:
	        - "db-data:/data/db"
    order:
        image: miguelangel299/practica2_gps:order
        depends_on:
	        - "mongo"
        deploy:
	        replicas: 1
	        resources:
	            limits:
	                cups: "0.3"
	                memory: 500M
	        restart_policy:
	            condition: on-failure
        ports:
	        - "8080:8080"
    web:
        image: miguelangel299/practica2_gps:web
        deploy:
	        replicas: 1
	        resources:
	            limits:
	                cups: "0.25"
	                memory: 300M
	        restart_policy:
	            condition: on-failure
        ports:
	        - "80:8080"

volumes:
    db-data:
